title: P2P Hack Club's Introduction to GitHub
description: P2P Hack Club's quick and fun introduction to GitHub. 100% dino approved.
template:
  name: orpheus's-science-project
  repo: introduction-to-github-template
  description: Dino + Science = Dino-mite
before:
  - type: updateBranchProtection
  - type: createIssue
    title: Getting Started with GitHub
    body: 00_introduction.md
    comments:
      - 00_assign-yourself.md
steps:
  - title: Assign yourself
    description: Assign the first issue to yourself.
    event: issues.assigned
    link: '{{ repoUrl }}/issues/1'
    actions:
      - type: gate
        left: '%payload.assignee.login%'
        operator: ===
        right: '%user.username%'
      - type: respond
        with: 01_turn-on-gh-pages.md
  - title: Turn on GitHub Pages
    description: Turn on GitHub Pages in the settings page of the repository.
    event: page_build
    link: '{{ repoUrl }}/issues/1'
    actions:
      - type: octokit
        method: repos.getPages
        owner: '%payload.repository.owner.login%'
        repo: '%payload.repository.name%'
        store:
          pagesUrl: '{{ result.data.html_url }}'
        action_id: pagesUrl
      - type: respond
        issue: Getting Started with GitHub
        with: 02_close-issue.md
  - title: Close an issue
    description: Cease a conversation by closing an issue.
    event: issues.closed
    link: '{{ repoUrl }}/issues/1'
    actions:
      - type: createIssue
        action_id: contrib_issue
        title: Your first contribution
        body: 03_your-first-contribution.md
        comments:
          - 03_create-a-branch.md
        data:
          thePayload: '%payload%'
      - type: respond
        with: 03_head-to-branch.md
        data:
          issueURL: '%actions.contrib_issue.data.html_url%'
  - title: Create a branch
    description: Create a branch for introducing new changes.
    event: create
    link: '{{ repoUrl }}/issues/2'
    actions:
      - type: respond
        issue: Your first contribution
        with: 04_commit-something.md
        data:
          thePayload: '%payload%'
  - title: Commit a file
    description: Commit your file to the branch.
    event: push
    link: '{{ repoUrl }}/issues/2'
    actions:
      - type: respond
        issue: Your first contribution
        with: 05_open-a-pr.md
        data:
          branch: '%payload.ref%'
          url: '%payload.repository.html_url%/compare/%payload.ref%?expand=1'
  - title: Open a pull request
    description: Open a pull request to propose your new file to the codebase.
    event: pull_request
    link: '{{ repoUrl }}/issues/2'
    actions:
      - type: gate
        gates:
          - left: '%payload.action%'
            operator: ===
            right: opened
          - left: '%payload.action%'
            operator: ===
            right: edited
          - left: '%payload.action%'
            operator: ===
            right: synchronize
      - type: closeIssue
        issue: Your first contribution
      - type: gate
        left: '%payload.pull_request.body%'
        else:
          - type: createReview
            body: 06_fix-body.md
            event: REQUEST_CHANGES
      - type: gate
        left: '%payload.pull_request.base.ref%'
        operator: ===
        right: main
        else:
          - type: createReview
            body: 06_fix-base.md
            event: REQUEST_CHANGES
      - type: getTree
        action_id: tree
        recursive: true
        sha: '%payload.pull_request.head.sha%'
      - type: gate
        left: '%actions.tree.data.tree%'
        operator: includes
        right: 'path:/info.html/'
        else:
          - type: createReview
            body: 06_fix-filename.md
            event: REQUEST_CHANGES
            data:
              expected: info.html
              url: '%payload.pull_request.html_url%/files'
      - type: createReview
        body: 06_request-changes.md
        event: COMMENT
        data:
          branch: '%payload.pull_request.head.ref%'
          url: '%payload.pull_request.html_url%/files'
  - title: Respond to a review
    description: Respond to a PR review.
    event: pull_request.synchronize
    link: '{{ repoUrl }}/pull/3'
    actions:
      - type: removeBranchProtection
      - type: createReview
        body: 07_pr-succeeds.md
        event: APPROVE
        data:
          branch: '%payload.pull_request.head.ref%'
  - title: Merge your pull request
    description: Make your changes live by merging your PR.
    event: pull_request.closed
    link: '{{ repoUrl }}/pull/3'
    actions:
      - type: gate
        left: '%payload.pull_request.merged%'
        else:
          - type: respond
            with: 08_reopen.md
      - type: respond
        with: 08_reminder-delete.md
tags:
  - Git
  - GitHub Pages
  - Branches
  - Commits
  - Pull Requests
  - Hack Club
  - P2P Hack Club
